mutex: mutex_test.cpp
	clang++ mutex_test.cpp -o mutex_test
	./mutex_test
synchronize: synchronize_test.cpp
	clang++ synchronize_test.cpp -o synchronize_test
	./synchronize_test
semaphore: semaphore_test.cpp
	clang++ semaphore_test.cpp -o semaphore_test
	./semaphore_test
producer_consumer: producer_consumer.cpp
	clang++ producer_consumer.cpp -o producer_consumer
	./producer_consumer
